+++
title = "Cards"
+++

The `cards` resource represents the payment cards with which users conduct transactions.
Cards are owned by users and communicate with the Marqeta platform over card networks such as Discover, MasterCard, and Visa.
Each card has a number of attributes, such as a primary account number (PAN), expiration date, and card verification value (CVV2).
Cards are derived from and controlled by a card product.

NOTE: For an overview of cards and the `card` object, see <</guides/cards/about_cards.adoc, About Cards>>.

## Create card
*Action:* POST +
*Endpoint:* /cards

Create a card using the `user_token` of the user that will own the card and the `card_product_token` of the card product that will control the card.
You must therefore create the user and card product before you can create the card.

NOTE: By default, newly created cards are inactive and must be explicitly activated (see Create Card Transition for information on activating cards). Alternatively, you can configure your card product's `config.card_life_cycle.activate_upon_issue` field such that cards are activated upon issue (see Card Products).

Submit a POST to `/pins/controltoken` to set the card PIN if your program requires PIN numbers (for example, for EMV cards); this action updates the `pin_is_set` field to "true" (see the "Create or Update PIN" section on this page for details).

### Query parameters
You can use optional query parameters to show both PAN and CVV2 number in the response.
If `show_pan` and `show_cvv_number` are set to "true", the fulfillment state of the card is DIGITALLY_PRESENTED instead of the normal initial state of ISSUED; this alternate state does not affect the delivery of physical cards.

[cols="10,10,10,50,20", options="header"]
|===
| Name | Type	| Required? |	Description |	Allowable Values
| show_pan | boolean | No | Set to true to show the full PAN in the response. | true &vert; *false*
| show_cvv_number	| boolean |	No | Set to true to show the CVV2 number in the response. |	true &vert; *false*
|===

### Sample request body
[source,json]
----
include::content/core/code_samples/cards_samples.adoc[tag=request]
----
### Sample response body
[source,json]
----
include::content/core/code_samples/cards_samples.adoc[tag=response]
----
