== Retrieve card

*Action:* `GET` +
*Endpoint:* `/cards/{token}`

Retrieve a specific card.

This endpoint supports field filtering and object expansion.

=== URL path parameters

|===
| Name | Type | Required? | Description | Allowable Values

| token | string | Yes | Identifies the card to retrieve. | Existing card token. <br> <br> Issue a `GET` to `/cards/user/{token}` to retrieve card tokens for a specific user.
|===

=== Sample response body

[source,json]
{
    "created_time": "2017-02-14T18:48:10Z",
    "last_modified_time": "2017-02-14T18:48:10Z",
    "token": "mytestcard01",
    "user_token": "my_user_01",
    "card_product_token": "red_cardproduct",
    "last_four": "8949",
    "pan": "111111______8949",
    "expiration": "0221",
    "expiration_time": "2021-02-28T23:59:59Z",
    "barcode": "17469201908992951865",
    "pin_is_set": false,
    "state": "UNACTIVATED",
    "state_reason": "New card",
    "expedite": false,
    "fulfillment_status": "ISSUED",
    "fulfillment": {
        "card_personalization": {
            "text": {
                "name_line_1": {
                    "value": "my line 1 text"
                },
                "name_line_2": {
                    "value": "my line 2 text"
                }
            },
            "images": {
                "card": {
                    "name": "my_card_logo.png",
                    "thermal_color": "Black"
                },
                "carrier": {
                    "name": "my_carrier_logo.png",
                    "message_1": "my message"
                },
                "signature": {
                    "name": "my_signature.png"
                },
                "carrier_return_window": {
                    "name": "my_return_address_image.png"
                }
            }
        }
    },
    "instrument_type": "PHYSICAL_MSR",
    "metadata": {
        "key1": "value1",
        "key2": "value2"
    }
}